@startuml resolve_inconsistent_remote_repository
title Resolve inconsistent remote repository
skinparam activity {
  BackgroundColor<< Succeeded >> lightgreen
  BackgroundColor<< Failed >> pink
}
(*) -> "Start sync"
  ->if "<Which method?>" then
    -->[tryPush()] if "<UnfetchedCommitExistsError>"
        -->[no] "(C)Synchronize normally"
      else
        -->[yes] "(A)Consistency Conflicts"
        if "<Check combine_db_strategy>" then
          -->[other strategies] "(D)Resolve inconsistent\nmanually" << Failed >>
        else
          -->[replace-with-ours] "(E)Resolve inconsistent\nby combineDB() automatically"
        endif
      endif
    else 
      -->[trySync()] if "<Which worker?>" then
        ---->[push_worker] if "<UnfetchedCommitExistsError>"
        -->[no] "(C)Synchronize normally"
      else 
        -->[yes] if "<Retry fetch>" then
          -->[failure] "(A')Consistency Conflicts"
        else
          -->[success] "(B)Transactional Conflicts"
          -->[retry] "(C)Synchronize normally" <<Succeeded>>
        endif
      endif
    else
      -->[sync_worker] if "<NoMergeBaseFoundError>"
        -->[no] "(C)Synchronize normally"
      else
        -->[yes] "(A')Consistency Conflicts"
        -->if "<Check combine_db_strategy>" then
          -->[nop] "(D)Resolve inconsistent\nmanually" << Failed >>
        else
          -->[other strategies] "(E)Resolve inconsistent\nby combineDB() automatically" << Succeeded >>
        endif
      endif
    endif
endif
@enduml